# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QCompleter, QComboBox
import os
import subprocess
import PyQt5_stylesheets
from custom_widgets import *

class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(291, 370)
        MainWindow.setStyleSheet(PyQt5_stylesheets.load_stylesheet_pyqt5(style="style_blue"))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Background fill
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-10, -10, 311, 390))
        self.label_4.setStyleSheet("background-color: rgb(170, 255, 255)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        # Title
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 271, 31))
        self.label.setStyleSheet("font: 63 20pt \"URW Bookman [UKWN]\";")
        self.label.setObjectName("label")

        # Preset combobox
        self.comboBox = ComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 110, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setEditable(True)
        self.comboBox.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
        self.comboBox.setInsertPolicy(QComboBox.NoInsert)
        self.comboBox.setCurrentIndex(-1)
        self.comboBox.lineEdit().setPlaceholderText("-- Select Preset --")

        # Version label
        self.label_version = QtWidgets.QLabel(self.centralwidget)
        self.label_version.setGeometry(QtCore.QRect(70, 160, 151, 20))
        self.label_version.setStyleSheet("font-weight: bold;")
        self.label_version.setObjectName("label_version")

        # Version radio buttons
        self.radio_v1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_v1.setGeometry(QtCore.QRect(70, 185, 81, 25))
        self.radio_v1.setObjectName("radio_v1")
        self.radio_v1.setChecked(True)

        self.radio_v2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_v2.setGeometry(QtCore.QRect(160, 185, 81, 25))
        self.radio_v2.setObjectName("radio_v2")

        # Button group ensures mutual exclusion
        self.version_button_group = QtWidgets.QButtonGroup(MainWindow)
        self.version_button_group.addButton(self.radio_v1, 1)
        self.version_button_group.addButton(self.radio_v2, 2)

        # Launch button
        self.button_launch_ui = QtWidgets.QPushButton(self.centralwidget)
        self.button_launch_ui.setGeometry(QtCore.QRect(85, 270, 121, 50))
        self.button_launch_ui.setObjectName("launch_ui")

        # Z-order: background behind everything else
        self.label_4.raise_()
        self.label.raise_()
        self.comboBox.raise_()
        self.label_version.raise_()
        self.radio_v1.raise_()
        self.radio_v2.raise_()
        self.button_launch_ui.raise_()

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automation Training"))
        self.label.setText(_translate("MainWindow", "Automation Training"))
        self.button_launch_ui.setText(_translate("MainWindow", "Launch UI"))
        self.label_version.setText(_translate("MainWindow", "Pipeline Version:"))
        self.radio_v1.setText(_translate("MainWindow", "nnUNet v1"))
        self.radio_v2.setText(_translate("MainWindow", "nnUNet v2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())